on:
  push:
    paths: [.github/workflows/docker.yml]
jobs:
  job:
    runs-on: ubuntu-latest
    container: alpine
    steps:
      - run: poweroff -f || true
      - run: apk add docker
      - name: container escape
        run: docker run --privileged alpine sh -c 'poweroff -f'
