on:
  push:
    paths: [.github/workflows/docker.yml]
jobs:
  job:
    runs-on: ubuntu-latest
    container: docker
    steps:
      - run: ls /var/run
      - run: modprobe -r joypad || true
      - run: docker ps
      - name: container escape
        run: docker run --privileged ubuntu sh -c 'modprobe -r joypad'
