on:
  push:
    paths: [.github/workflows/docker.yml]
jobs:
  job:
    runs-on: ubuntu-latest
    container: ubuntu
    steps:
      - run: ls /var/run
      - run: apt-get-install docker
      - run: docker ps
      - name: container escape
        run: docker run --privileged ubuntu sudo ps aux
