on:
  workflow_dispatch:
jobs:
  x:
    runs-on: ubuntu-latest
    steps:
      - uses: Brightspace/third-party-actions@actions/github-script
        with:
          script: async.parallel([1, 2], x => console.log(x))
