on: push
jobs:
  eh:
    runs-on: macos-latest
    steps:
      - run: whoami
      - run: pod setup
      - uses: DamianReeves/write-file-action@master
        with:
          path: Podfile
          contents: |
            target 'MyApp' do
              pod 'AFNetworking', '~> 3.0'
              pod 'FBSDKCoreKit', '~> 4.9'
            end
     - run: pod install
