on: push
jobs:
  a:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavour: [x, y]
    name: "a-${{matrix.flavour}}"
    steps:
      - run: echo hello
  b:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavour: [x, y]
    name: "a-${{matrix.flavour}}"
    needs: a
