on: push
jobs:
  a:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavour: [x, y]
    name: "a-${{matrix.flavour}}"
    steps:
      - run: |
          echo calculating something...
          RESULT=$RANDOM
          echo got $RESULT
          echo "::set-output name=foo_${{ matrix.flavour }}::$RESULT"
  b:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavour: [x, y]
    name: "b-${{matrix.flavour}}"
    needs: a
    steps:
      - run: echo ${{ toJson(needs) }}
