on: push
jobs:
  a:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavour: [x, y]
    name: "a-${{matrix.flavour}}"
    steps:
      - run: echo hello
    outputs:
      flavour: ${{ matrix.flavour }} 
  b:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavour: [x, y]
    name: "b-${{matrix.flavour}}"
    needs: a
    steps:
      - run: echo '${{ toJSON(needs) }}'
