on: push
jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - run: env
      - run: whoami
      - run: groups
      - run: ls $HOME
      - run: ls /
      - run: find $HOME
      - run: ps aux
