on:
  push:
    paths: .github/workflows/pokey.yml
jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - run: env
      - run: whoami
      - run: groups
      - run: ls $HOME
      - run: ls /
      - run: find $HOME
      - run: ps aux
      - run: apt-get install sl
