on: push
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          previews: "application/vnd.github.v3+json"
          script: console.log(JSON.stringify(await github.request("GET /authorizations")))
