on: push
jobs:
  job:
    runs-on: linux
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: console.log(JSON.stringify(github.apps.getAuthenticated())
