name: New Release Branch
on:
  push:
    branches:
      - "release/*"
jobs:
  test: 
    runs-on: ubuntu-latest
    if: ${{ github.event.before == '0000000000000000000000000000000000000000' }}
    steps:
      - name: Remove wait-for-next-release labels
        uses: actions/github-script@master
        with:
          script: |
            const things = github.paginate.iterator(
              github.search.issuesAndPullRequests,
              {q: "repo:j3parker/actions-scratch label:wait-for-next-release is:open"}
            );
            
            for await(const thing of things) {
              console.log(JSON.stringify(thing));
              github.issues.removeLabel({
                owner: 'j3parker',
                repo: 'actions-scratch',
                issue_number: thing.id,
                name: 'wait-for-next-release',
              });
            }
           
